### ISSUE TITLE
About the action space

### ISSUE THREAD

**Issue by ewanlee** [Ceruleanacg/Personae#4]
I think the action space should be `3 ** self.codes_count` rather than `self.codes_count * 3` ?

**Comment by Ceruleanacg** [comment]
For DDPG, the action space is `self.codes_count * 3`, because here DDPG is implemented for continues action space, so here for each stock code, the action is [-1, 1] which represents the possibility of taking each action.

For PolicyGradient, the action space is still `self.codes * 3`, because in fact, we can only take one action for each state, the same to DDPG, so you may find some logical problems in DDPG, because DDPG tries to do `self.codes` actions in one state, that is not reasonable.

So I implemented method for test `forward_v2` to avoid this problem.

Thank you very much.

**Comment by ewanlee** [comment]
I am sorry I did not read the code carefully. I have the last two questions:
1.  What is your purpose for compare `self.trader.action_times` and `self.code_count` ?
2. Whether or not the PolicyGradient will prematurely converge to a local optimum if you set `use_prob` always False?

**Comment by ewanlee** [comment]
Alright, thank you very much 👍
